version: '3'

services:
  db:
    build: ./db
    networks:
            - testing_net
    restart: always
    volumes:
        - $HOME/pgvol:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB: db_tsc5
    - POSTGRES_USER: postgres
    - POSTGRES_PASSWORD: docker
  

  web:
    build: .
    environment:
        DB_HOST: db
        DB_PORT: 5432
        DB_USERNAME: postgres
        DB_PASSWORD: docker
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always
    links:
      - db:db
    networks:
            - testing_net

networks:
    testing_net: