module.exports = [
  'Huertas urbanas',
  'Alimentos y bebidas',
  'Arte y cultura',
  'Autopartistas',
  'Cuidados y servicios comunitarios',
  'Carpintería',
  'Comercializadoras: mercados, ferias o almacenes populares',
  'Comunicación radial',
  'Comunicación audiovisual',
  'Comunicación escrita',
  'Construcción',
  'Cosméticos',
  'Cuero',
  'Deporte y recreación',
  'Educación',
  'Eléctrico',
  'Electromecánico',
  'Electrónico',
  'Electrodomésticos',
  'Energía',
  'Entretenimiento',
  'Ferretería',
  'Gastronomía/Hotelería',
  'Gráfico',
  'Librería',
  'Limpieza',
  'Mantenimiento',
  'Mascotas',
  'Metalmecánico',
  'Papel',
  'Peluquería',
  'Plásticos',
  'Portuario',
  'Salud',
  'Sanitario',
  'Supermercado',
  'Textil',
  'Turismo',
  'Vivienda',
  'Trabajadorxs de la vía pública',
  'Feriante',
  'Cuidados y servicios'
].map(businessArea => ({ descripcion: businessArea }));
